"""add password rest

Revision ID: 03ab3500c1dc
Revises: 244b3128d9d4
Create Date: 2026-01-12 11:09:03.996271

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "03ab3500c1dc"
down_revision = "244b3128d9d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_resets",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("password_resets")
    # ### end Alembic commands ###
