"""fresh start

Revision ID: 244b3128d9d4
Revises:
Create Date: 2026-01-12 10:56:02.184320

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "244b3128d9d4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("profile_path", sa.String(length=255), nullable=True),
        sa.Column("role", sa.Boolean(), nullable=True),
        sa.Column("dob", sa.DateTime(), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("lock_flg", sa.Boolean(), nullable=True),
        sa.Column("lock_count", sa.Integer(), nullable=True),
        sa.Column("last_lock_at", sa.DateTime(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("create_user_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_user_id", sa.BigInteger(), nullable=True),
        sa.Column("deleted_user_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["create_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "posts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("create_user_id", sa.BigInteger(), nullable=False),
        sa.Column("updated_user_id", sa.BigInteger(), nullable=False),
        sa.Column("deleted_user_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["create_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts")
    op.drop_table("users")
    # ### end Alembic commands ###
